Docking behaviour fixes
ClemensElflein/open_mower_ros pull request #26
Opened 2023-05-01 14:23 UTC by olliewalsh

Wait for GPS in docking approach.

If docking approach fails, it's not safe to undock, so just retry docking. Reset retry count after docking approach.

When starting mowing, only undock if docked, otherwise just start mowing.

If docking needed, e.g low battery, do not abort the current behaviour if it's already docking/undocking.

2023-05-01 16:40 UTC, ClemensElflein requested changes

2023-05-01 16:40 UTC, ClemensElflein commented on src/mower_logic/src/mower_logic/mower_logic.cpp
> +                currentBehavior->state_name() != "UNDOCKING"
it's better to actually compare the instances in case we change the state name in the future.
i.e. do something like `currentBehavior != &UndockingBehavior::INSTANCE`

2023-05-01 16:41 UTC, ClemensElflein commented
Thank you for the PR, the changes look good for me, I'd just propose a small change for checking for the current state (see comment above)

2023-05-01 17:38 UTC, olliewalsh commented on src/mower_logic/src/mower_logic/behaviors/DockingBehavior.cpp
> +    if(!isGPSGood){
should call it

2023-05-01 17:47 UTC, olliewalsh commented on src/mower_logic/src/mower_logic/behaviors/DockingBehavior.cpp
> +    if(!isGPSGood){
works without it so will remove for now

2023-05-01 18:19 UTC, olliewalsh commented on src/mower_logic/src/mower_logic/behaviors/DockingBehavior.cpp
> +    if(!isGPSGood){
ah, it gets reset when entering the instance. Need to just wait in a loop instead

2023-05-01 19:23 UTC, olliewalsh commented
seems to be working ok but set to draft until I can test this a couple of more times

2023-05-02 21:51 UTC, ClemensElflein commented
alright, looks good to me. let me know once it's confirmed working

2023-05-03 08:17 UTC, olliewalsh commented
Ran for a day with zero docking issues. Previously would fail quite often, depended on the dock approach distance as it was a race to dock before the voltage drops back down below the threshold

2023-05-03 15:12 UTC, ClemensElflein commented
sounds good, you should probably increase the empty voltage threshold though

2023-05-03 15:24 UTC, olliewalsh commented
yeah, I did increase it a little when not trying to reproduce this (there is an issue with that, will submit a PR soon)

2023-05-03 21:44 UTC, merged