Fix/gps throttle message
ClemensElflein/open_mower_ros pull request #51
Opened 2023-08-07 14:29 UTC by alexvaut

This goes along with https://github.com/ClemensElflein/xbot_positioning/pull/3 to reduce the amount of gps messages when not needed.

2023-08-08 09:39 UTC, ClemensElflein commented
Thank you for the PR! I think we can set it to a large value like every minute or even larger by default. This was basically only for me to see if switching on GPS works reliably.

2023-10-13 22:58 UTC, olliewalsh requested changes

2023-10-13 22:58 UTC, olliewalsh commented on src/mower_logic/src/mower_logic/mower_logic.cpp
> +        ROS_WARN_STREAM_THROTTLE(last_config.gps_message_throttle,"Low quality GPS");
Could leave it as it but  just not log it when `!currentBehavior->needs_gps())`?

2024-03-10 17:24 UTC, ClemensElflein commented
I have merged the xbot_positioning PR.

I agree with olliewalsh that we should only print it, when GPS is actually needed

2025-03-16 13:21 UTC, rovo89 commented
Does this really need to be configurable?

2026-06-18 11:51 UTC, closed without merging

2026-06-18 11:51 UTC, ClemensElflein commented
stale PR